# Generated by Django 4.2.4 on 2023-12-06 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoB3',
            fields=[
                ('sigla', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='ok@ok.com', max_length=250)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('periodicidade', models.IntegerField()),
                ('ultimo_valor', models.IntegerField(blank=True, null=True)),
                ('limiteSuperior', models.IntegerField(default=0)),
                ('limiteInferior', models.IntegerField(default=0)),
                ('ativoB3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.ativob3')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.investidor')),
            ],
        ),
    ]
