# Generated by Django 4.2.4 on 2023-12-07 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_remove_monitoracao_ultimo_valor_cotacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='ativoB3',
            new_name='monitoracao',
        ),
    ]
