# Generated by Django 4.2.4 on 2023-12-07 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_rename_ativob3_cotacao_monitoracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='cpf',
        ),
        migrations.AddField(
            model_name='investidor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='investidor',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
