"""
Django settings for hermes project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR.parent / 'data' / 'web'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "v8@#um6@$$agk54ex(+uqagnk)s(#ct@=-bki7)eeqr3ry_+yj"
# SECRET_KEY = os.getenv('SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = bool(int(os.getenv('DEBUG', 0)))
DEBUG = 1

ALLOWED_HOSTS = [
    '127.0.0.1', 'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'celery',
    # 'django_celery_beat',
    'cotacao.apps.CotacaoConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hermes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hermes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': os.getenv('DB_ENGINE', 'change-me'),
        # 'NAME': os.getenv('POSTGRES_DB', 'change-me'),
        # 'USER': os.getenv('POSTGRES_USER', 'change-me'),
        # 'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'change-me'),
        # 'HOST': os.getenv('POSTGRES_HOST', 'change-me'),
        # 'PORT': os.getenv('POSTGRES_PORT', 'change-me'),        
        'ENGINE': "django.db.backends.postgresql",
        'NAME': "hermes_db",
        'USER': "hermes_user",
        'PASSWORD': "123456",
        'HOST': "localhost",
        'PORT': "5432"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# # /data/web/static
# STATIC_ROOT = DATA_DIR / 'static'
# # /data/web/media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')# Here
MEDIA_URL = '/media/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'templates/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# e-mail settings
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'pedro.daltro@gmail.com'
EMAIL_HOST_PASSWORD = 'tkyuibcnuzsjiwsf'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# set CELERY settings with CELERY_{}
# user = os.getenv('RABBITMQ_DEFAULT_USER')
# password = os.getenv('RABBITMQ_DEFAULT_PASS')
# CELERY_BROKER_URL = "amqp://guest:guest@rabbitmq:5672/"
# CELERY_TIMEZONE = 'Asia/Seoul'
# CELERY_ENABLE_UTC = False
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_ACCEPT_CONTENT = ['json']
